import { Language } from '@/types';

export const LANGUAGES: Language[] = [
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C',
  'C++',
  'C#',
  'Go',
  'Rust',
  'Ruby',
  'PHP',
  'Swift',
  'Kotlin',
  'HTML',
  'CSS',
  'SQL',
  'Shell',
  'Markdown',
  'JSON',
  'YAML',
  'Dart',
  'Other',
];

export const LANGUAGE_COLORS: Record<Language, string> = {
  JavaScript: '#F7DF1E',
  TypeScript: '#3178C6',
  Python: '#3776AB',
  Java: '#007396',
  C: '#A8B9CC',
  'C++': '#F34B7D',
  'C#': '#239120',
  Go: '#00ADD8',
  Rust: '#CE422B',
  Ruby: '#CC342D',
  PHP: '#777BB4',
  Swift: '#FA7343',
  Kotlin: '#7F52FF',
  HTML: '#E34F26',
  CSS: '#1572B6',
  SQL: '#4479A1',
  Shell: '#89E051',
  Markdown: '#083FA1',
  JSON: '#F5C518',
  YAML: '#CB171E',
  Dart: '#0175C2',
  Other: '#64748B',
};

export const LANGUAGE_EXTENSIONS: Record<Language, string> = {
  JavaScript: '.js',
  TypeScript: '.ts',
  Python: '.py',
  Java: '.java',
  C: '.c',
  'C++': '.cpp',
  'C#': '.cs',
  Go: '.go',
  Rust: '.rs',
  Ruby: '.rb',
  PHP: '.php',
  Swift: '.swift',
  Kotlin: '.kt',
  HTML: '.html',
  CSS: '.css',
  SQL: '.sql',
  Shell: '.sh',
  Markdown: '.md',
  JSON: '.json',
  YAML: '.yaml',
  Dart: '.dart',
  Other: '.txt',
};
